language: r
dist: trusty
sudo: false
branches:
  only:
  - master
cache:
  packages: true
  directories:
  - "$HOME/bin"
before_script:
- Rscript -e 'blogdown::install_hugo()'
script:
- Rscript -e 'blogdown::build_site()'
deploy:
  provider: s3
  access_key_id:
    secure: W3gRO2jctIZ6QDaDVz7eb3xm0Fom3z47IiVrgt7qbFALsGKUjbiHCIYX5ZwTLKdrOqVItD0KfGQnGbwXpR1tbnf8CB4qyiJ9BXhDTlMwQoqhDoM6d1friWuAXKJTqtIdA5hg+uT909kur5r4XXFxfMg/1HrPyjjLX80Mi2pVNH7bmkR+vn/lQ2CWzgj0f10tP1Utuw6sWbmN3IzgsCvuE9VwX1DwZw9RTAfotYR9ZuCWwk6hEbsa4sDVjss1WazAK+f0lkKQVYpXMeNxQUaR12//RwhobBFeAYotKCnUf6WM/eav2uP2jM2McXdve70d1D1ieeO1VguQM7xNhFY25OcGeJeYhXTb+IUGoiM+hwLUlpo6iliBMN4NyZtVqiPnZMSEHmy0ljPocJO0mjh+ebinj+1FfhFSUc+sCS7edzObaL+mFA1b8UrFJgQSDq5RAwCuPOJLErUYs5gAVhdbTqKr+8sSdkRdMjUHbkIUAWLVnwvMdo+rx3ujY87e4GwNNLgD2UlLDD0exwP+pCvkxM5v1MUafNuuvSamJKZNCFxoJebu+6xwEVEmBR5ZpX3jD1zb/+98FP5LQZ1Grut00xoB5XZaNqcOezZEgbo8qvCpeYQu3CKnnZKHvj1DJuwc7h5xMlyvFZ7uPKoMFhWLrzMS1APnS0wFuDeofsUn9x4=
  secret_access_key:
    secure: GO40EvCjRqcZNSINyV8FWMax2Mj08HRLi3cucvKNUldL3JtKi4h0OSfRs2SiVdQB5Rv7XL7WSf+/qXcjSFPfwjlClPT9lubOKEEYsq2I30WqpFfmCJiKhxU5D/VVI4Gytz3AWtinOPYELCI/XTVP5B6DWqpjpH3WR6lPP0kF8C51Hn9DZGpide4IKkOGmwBfSZvbYGjHlsLpUVxNVNuTlj6+wa35tMwu5UUAaK/GVNQMLJo5qSLfHufUkW07X1/Xqu+5juqtERri8El2dwazd/SLyNStzhjWu4aOytXvnZwM+TrINztxsm6viXfrZpEdbU/q+EENyEG2o/8mDeQd1mH3SsE7Jcq+lE3PTOz8alDOehG3wbcipknNkQXi0tHDzbOKtBNab83gnJwT4Galngym8+GydrC9T+YG0iJ2eqWcGUrBP7wR8pLb3cH1yU/EFW3RKmMDXD/gCTyBqQVX3RP+VSS2IfLyI9raUmq93sNd5gMea/gC+DY+p8Ei1ZrNUCcszdcVG9RM7PM849rrNReyk9uEzUH8Hy9ICi8z5CXO585cKjDdVndw49C6T7PsLcLZSMmENRxd36M+9UZ8lyL4Rketxsv3E6SNYHdA0xEgPFcYMXpfQJa7+lc6EJGw00EMahfBdUJ4ktKGPkXBx8pnlqUQ1ebftsLfyFw9LpU=
  bucket: grobins.me
  acl: public_read
  on:
    repo: grobins/grobins-blog
notifications:
  slack:
    secure: R6825dTtz7/pSQPJ8T9YX6vOxjwVFfYLuWfrSdlrfbf47b4m/tRvBZwTqVf+/tS6B+Uvc4xGjyVEasPYEPsscwBF2gPj0mIOzz1gPtQ62kWZrJM+sMJEC1MZcl/hlQKaz0MdRc067UUZvL3eW2vV7pbN2QRd4diOhDuMo4QqcwB/GyACU6pPbUIgp2aANRlibpAH9I/SqO/OJCn6N/Dtk648xHoiN3jwewnFZ13MEKEMavnkq1GXo9SwLM9tuH2j3QivA2hCacooIMpH3DER1Mqk2g/eFOe3cZRlHDiobhF+whDB3p36b9Piw5pSLvISuI8IfoLl6INundkg5zxrQj8Ah83ygvVpJy9QXHOPqpnU3dotfUCj1m35VFDxdMmUgu9zJ/dKm62kiMLjTQg0+klsKu1Kyq7EqdTS0z5fw7H4GPjkmbQ0y4x14dGU5YCB1FXDICAg5hwSUjiEIDLaWb20Y2K+PUpE4HGeuTpu/eWGoH5iemSiSLxbzlVpm1boL0ZBvfZd7172iRjUnRZm40xym7O3spGs0kcc5fWz9vbtorJzgfb9FnmyRbOUZqZDgINe0LNjzLxsLhQIRvVmPVpsOUuITqb49ICLatyfu/z7fuWww3jlzWf9kE2wHARyXTNnIQUP4RfqsZ51CSd9oxpRbwiA3D67tqspZHkJUu8=
