language: r
dist: trusty
sudo: false
branches:
  only:
  - master
cache:
  packages: true
  directories:
  - "$HOME/bin"
before_script:
- Rscript -e 'blogdown::install_hugo()'
script:
- Rscript -e 'blogdown::build_site()'
deploy:
  provider: s3
  access_key_id: bJsqupKDiDBl2t3eRFoy2/vKnl1meMF9UW2hoLIt
  secret_access_key:
    secure: Brrne7iWgEU9XIIsncmJHvld+2oTqZBtoc2yHQujT3p1a2QqTRTzRgHAydsG98BqM4Nj1GYMRLacWX1Du51dSNsWYZIp8oh5a0whzoJdiL6HQ/pEzyqvpdshYoCcmcWFLjhEQzbJFPrBNGzOU+9Pt+TqtaWNpK8tJbdi8RIQNVBXaqP58LNX0UWJln6JRQhwdaf6gDuMF+IP91ifhtguGWxcQfSJCYSsgMhan0mvIu/nNgbefQxRF1+Pgz37eb8rAYABPWte18N5eRA1I6564dmqTQJds6keuc6yca4Yz63yeKIfbnjjGlrtYe2slIVWtQox1H9RppnH5rHYk2Rft+KV475VELXbqr+dWZjcGYvuym5YaEUS1oDNDKZN+uBoMN6PUkA9iU8nnCPyERaz8jpihev1O0CALgrJQlXHe/4ohGpFfe/819bBZmYcE9C0USzMrAANIATTgQnDZ0X6raWZSH+Od2doQooa2RWEylnQ6Ie5U46pKPQgKI4TxRPFqkZOgbGll0mk11Z3rjLElpaKKHa1ApYUSij1jzQIDO/i21J2cTdxNE09cwWfIXcizJfgkcf8/L/jmaS0CP4E9O6v2VuWv08J2YaVrrxAQJ0CTpThM8bxpv0gkdGpMg+tJxen6BySYQUE4L0v04W1pyTvBjzHbh4P6Q6R7MKsAKQ=
  bucket: grobins-testtravisdeloy
  # acl: public_read
  on:
    repo: grobins/grobins-blog
