language: r
dist: trusty
sudo: false
branches:
  only:
  - master
cache:
  packages: true
  directories:
  - "$HOME/bin"
before_script:
- Rscript -e 'blogdown::install_hugo()'
script:
- Rscript -e 'blogdown::build_site()'
deploy:
  provider: s3
  access_key_id: nXhfAPKlF7u+48pWuflYiaNvgjucPZ9akjrpLAfgg7pCLfqWuvLfdSByhB7s9mw0tqT/lcH3xCuEtAcV96dvlE8f98r8NTX/Fr/lgOiSs97M+v/f52Kr7IkIFh8SoCwByCpwd7+0pjxj/IG1KpjtdguazblrM0K4nzi4/LSv5ek62YvmEH51Hp+SY0mWdI+reTtmHrFDXwLvEGID/07B7mXRIGNhJh600FWf+KubvQRmw0cZhyynT6Fjwa9XLPqI77yTOj9so+labTZbsbDONWJdoWQJnCXmTa3ZvWeXJf94AIS6gfIajJZYaYT3aeynFAYR9rm+lYK2u+0qVu+W8YMPSlKSRjwvxJAy5cWuC6Lnjkhi35rTpk+33e9DnHPX7r8EztNzZlfiBF89aVBsr5E5M4KlGrB06FRO/DlkdY2XQgetj6q90qVlx0N1czSrb6R9B2rPIi7QlkG+BSjWNfMuVEC066uZbQ8sgxl3JZFwvfgLIvvHe2BKjwxH87Jb1EAE7PBssNQmgWdGAhrESAp7I6YWSI8ez79pz6mSaYoxR5KCLR2h83GBrgDZ+BqifP7I56PGgdRINYpGWc+HKNqtlHUXvtZwC5NTjFvxFJgl60fYy2ceGYWdBdb5uBRhuOG5W6V6uTk8pBZWcbGaFpA2HrNahU1twjS9hGvuvHE=
  secret_access_key:
    secure: E4NPqGsfeU/tWEL/kBv+1/oJd/iAMhQHGpv9tT5QgfpVXF1uj5s11YwkXLbZuZIqUCytZC1kvtk/6xBJ2BXeTcsF+62En2h7RB9C1SfqZwKSqyzoRZnJV5Nc3j0OHc0O7ZWtRTGZ+c1d/xisDausc3DiBfgBn+warcNjkg4deUDSmkhn5in0jmUTRgW480ah/L/xnNsvrnwVMDAKbw1BpsfxE5wQSGM0r/bMObci2EmzXWyQ/P3dhNBPPeu3AvvOsJHqr73fv+vrmHMXZNKf9cKQvfBmLn+S65H/fPND7Mm3DxSpqh17rak0b6vA22qvqLzWlUx5DVxdohHiZ0HqYiSMrteTANHG92r+NzSRdm6m/U2pQj1dImTmyKOXVJiBbWKwp2hqmkPo7bn8hemQB22slKrhgDLo8onY77EgUrGPVg7U+1XIyt7Dc/CKvIIhap+oH0dO6WUfdjF5OJPTGFD9JkIIIjmagCse3NE3L/azyLF3IpxSOPI1anzVLP846snPeteJ8Ae6j8Jy1qUq/GYZR14/Bk/vnn+FhOBBaDBv3FavQ3hrvUFN2Kp+nhUXA0YMsjzZjqkAhtQHoc/BM1zUzbo5JzPN5Bo3oeXGj2yqNwPgvePKMq9nm9JN+FQLPVc87s/b3D98vVtJWAdf29fH6mKMoye7QWlBU/19fAg=
  bucket: grobins-testtravisdeloy
  acl: public_read
  on:
    repo: grobins/grobins-blog
